spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        new_generator_mappings: false
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: true
  datasource:
    url: jdbc:mysql://reevoo-test-beta.crvfzsr4389e.us-east-1.rds.amazonaws.com:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CST
    username: admin
    password: reevoo2020
#    url: jdbc:mysql://127.0.0.1:3306/url?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CST
#    username: root
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      uri: mongodb://test:test@127.0.0.1:27017/url?authSource=mydb
server:
  port: 4000
  tomcat:
    uri-encoding: UTF-8
