jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD:}
    algorithm: PBEWithMD5AndDES
spring:
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        new_generator_mappings: false
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: true
    open-in-view: false
  datasource:
    url: ENC(grMCWwygMDkOd+TdWje1yasCGpnL/JAKA5z6DNllIeRt/Yr3G5LFPlcztotvLWKe+ogRiCvrjGjJ/y8FwFuhHfPpaTZuxBkIJRgmQOZaqLK+HAWyibUZ9RNp8a6xCao5LDmK/VFWCY6rAme0f+K55I3Nkh1J7IgiYd4cENiE+r+ejehGjqwyDs2UeOp/NpGJUUQ7B74dehI=)
    username: admin
    password: ENC(ivdNWO7aivOZyhIlIDGUB/0lYCbyuE7g)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    mongodb:
      host: ENC(AP/xA3bZVKzsP9wTKpZHgbz1tf9TGCpu)
      port: 27017
      authentication-database: url
      database: url
      username: url
      password: ENC(OAOND8tNccLS/N13zbCFj/RSwejoI/Hr)
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
management:
  endpoint:
    health:
      show-details: always
  metrics:
    enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  config: classpath:log4j2.xml
