# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Continuous Integration

on:
 [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Run the Maven verify phase
      env:
        JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      run: mvn -B verify --file backend/pom.xml
    - name: Build with Maven
      env:
        JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      run: mvn -B package --file backend/pom.xml
    - name: Run java checkstyle
      uses: nikitasavinov/checkstyle-action@0.3.0
      with:
        # Report level for reviewdog [info,warning,error]
        level: warning
        # Reporter of reviewdog command [github-pr-check,github-pr-review]
        reporter: github-pr-review
        # Filtering for the reviewdog command [added,diff_context,file,nofilter].
        filter_mode: added
        # Exit code for reviewdog when errors are found [true,false]
        fail_on_error: true
        # Checkstyle config file
        checkstyle_config: google_checks.xml
        # Working directory relative to the root directory.
        workdir: ./backend
        # Tool name to use for reviewdog reporter
        tool_name: reviewdog
  test_redirect:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.2
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_MYSQL_URL: ${{secrets.MYSQL_URL}}
        envkey_MONGO_URL: ${{secrets.MONGO_URL}}
        file_name: redirectService/credentials.env
    - name: Run Go testing
      working-directory: redirectService
      run: go test ./...
      env:
       TEST_DIR: ../
  test_visitLog:
    runs-on: ubuntu-latest
    steps:    
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.2
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_MYSQL_URL: ${{secrets.MYSQL_URL}}
        envkey_MONGO_URL: ${{secrets.MONGO_URL}}
        envkey_BOOTSTRAP_SERVERS: localhost:9092
        envkey_KAFKA_GROUP: mygroup
        envkey_KAFKA_TOPIC: visitLog
        file_name: logService/credentials.env
    - name: Run Go testing
      working-directory: logService
      run: go test ./...
      env:
       TEST_DIR: ../
    
