name: Release for docker

on:
  push:
    branches: [ govioledo]

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        env:
          JASYPT_ENCRYPTOR_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: mvn -B clean package --file backend/pom.xml
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }}
             -p ${{ secrets.DOCKER_PASS }}
      - name: Build Docker image
        run: docker build -t reevoo2020/visitlog-service:1.1 .
      - name: Publish Docker image
        run: docker push reevoo2020/visitlog-service